<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLa9ynoa\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLa9ynoa/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLa9ynoa.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLa9ynoa\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLa9ynoa\appDevDebugProjectContainer([
    'container.build_hash' => 'La9ynoa',
    'container.build_id' => 'c8311fb8',
    'container.build_time' => 1581437099,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLa9ynoa');
