<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

<<<<<<< HEAD
if (\class_exists(\Container05szson\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container05szson/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container05szson.legacy');
=======
if (\class_exists(\ContainerKbkggyi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKbkggyi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKbkggyi.legacy');
>>>>>>> 10d837b11ef88388e3929edaa871f347e6438af7

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
<<<<<<< HEAD
    \class_alias(\Container05szson\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container05szson\appDevDebugProjectContainer([
    'container.build_hash' => '05szson',
    'container.build_id' => '6b6d4857',
    'container.build_time' => 1581984339,
], __DIR__.\DIRECTORY_SEPARATOR.'Container05szson');
=======
    \class_alias(\ContainerKbkggyi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKbkggyi\appDevDebugProjectContainer([
    'container.build_hash' => 'Kbkggyi',
    'container.build_id' => '56c04d74',
    'container.build_time' => 1581968686,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKbkggyi');
>>>>>>> 10d837b11ef88388e3929edaa871f347e6438af7
