<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKbkggyi\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKbkggyi/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKbkggyi.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKbkggyi\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKbkggyi\appDevDebugProjectContainer([
    'container.build_hash' => 'Kbkggyi',
    'container.build_id' => '56c04d74',
    'container.build_time' => 1581968686,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKbkggyi');
